name: project_portfolio
description: Oscar Newman's project portfolio.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.0
#  google_fonts: ^2.0.0
  url_launcher: ^6.0.3
  # material_design_icons_flutter: ^4.0.5955 # Not null safe yet
  font_awesome_flutter: ^9.0.0 # Substitute for material_design_icons_flutter while null safety missing
  provider: ^5.0.0
  fluttertoast: ^8.0.5
  intl: ^0.17.0
  flutter_native_splash: ^1.1.8+4
  printing: ^5.1.0 # PDF package imported within Printing

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/cv_assets/

